# Generated by Django 3.2.25 on 2024-10-14 01:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='unique_id',
            field=models.CharField(default=app.models.generate_unique_id, editable=False, max_length=6, unique=True),
        ),
    ]
