# Generated by Django 3.2.25 on 2024-10-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
