# Generated by Django 3.2.25 on 2024-10-16 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_platformaccount_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='gateway',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_id', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('routing_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=255)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_country', models.CharField(max_length=2)),
                ('billing_line1', models.CharField(max_length=255)),
                ('billing_district', models.CharField(max_length=255)),
                ('billing_postal_code', models.CharField(max_length=20)),
                ('bank_address_line1', models.CharField(max_length=255)),
                ('bank_address_city', models.CharField(max_length=255)),
                ('bank_address_country', models.CharField(max_length=2)),
                ('bank_address_district', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
