# Generated by Django 3.2.25 on 2024-10-11 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usd_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
