# Generated by Django 3.2.25 on 2024-10-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_beneficiary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_account_id',
        ),
    ]
