# Generated by Django 3.2.25 on 2024-10-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_beneficiary_bank_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='account_number',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
