# Generated by Django 3.2.25 on 2024-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20241022_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='bank_account_number',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
