# Generated by Django 3.2.25 on 2024-10-22 03:41

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20241022_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='bank_address_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_address_country',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_address_district',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='bank_address_line1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='billing_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='billing_country',
            field=models.CharField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='billing_district',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='billing_line1',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='billing_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='billing_postal_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, validators=[django.core.validators.RegexValidator(message='Account number must be numeric.', regex='^\\d+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='routing_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, validators=[django.core.validators.RegexValidator(message='Account number must be numeric.', regex='^\\d+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='account_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Account number must be numeric.', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='linkedaccount',
            name='routing_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Account number must be numeric.', regex='^\\d+$')]),
        ),
    ]
