# Generated by Django 3.2.25 on 2024-10-23 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20241022_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedaccount',
            name='bank_account_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
